### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by zoffixznet** [ramiroencinas/perl6-FileSystem-Capacity#3]
From [`#perl6`](https://irclog.perlgeek.de/perl6/2016-12-05#i_13686128)
> `_ramix_`	Hi. I need to change the module name: https://modules.perl6.org/dist/F​ileSystem::Capacity::VolumesInfo by https://modules.perl6.org/​dist/FileSystem::Capacity, is it possible?

Yes, just change it [in your META file](https://github.com/ramiroencinas/perl6-FileSystem-Capacity/blob/06ef070d087279213c552155928ce1999924264f/META.info#L3). However, your [module](https://github.com/ramiroencinas/perl6-FileSystem-Capacity/blob/06ef070d087279213c552155928ce1999924264f/lib/FileSystem/Capacity/VolumesInfo.pm6) *is* named `Filesystem::Capacity::VolumesInfo` so ensure you tell your users to `use` the right name.

**Comment by ramiroencinas** [comment]
I have just adapted the module name in my META.info and the corresponding instructions in README.md

**Comment by zoffixznet** [comment]
And it updated in the ecosystem: http://modules.perl6.org/#q=FileSystem%3A%3ACapacity
